#!/usr/bin/python
#	vim:fileencoding=utf-8
# Handle INSTALL_MASK setting in make.conf.
# (c) 2011 Michał Górny <mgorny@gentoo.org>
# Released under the terms of the 2-clause BSD license.

import sys

try:
	from installmask.cli import main
except ImportError:
	import os.path
	sys.path.insert(0, os.path.dirname(__file__))
	# Ensure a clean reload from the new location.
	if 'installmask' in sys.modules:
		try: # py3 compat
			from imp import reload
		except ImportError:
			pass

		reload(sys.modules['installmask'])
		del sys.modules['installmask']
	from installmask.cli import main

if __name__ == '__main__':
	sys.exit(main(sys.argv))
